server {
    listen 80;
    listen [::]:80;
    server_name pct.test.ptfin.ru;
    charset utf-8;

    resolver ipv6=off valid=40s 188.120.247.2 188.120.247.8 82.146.59.250;
    resolver_timeout 20s;

    gzip on;
    gzip_vary on;
    gzip_disable "msie6";
    gzip_comp_level 6;
    gzip_min_length 1100;
    gzip_buffers 16 8k;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        text/js
        text/xml
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss;

    location ~ /.well-known {
        root /usr/share/nginx/html;
        allow all;
    }

    location / {
        proxy_pass http://127.0.0.1:8110;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        send_timeout 60s;
    }

    location ~ /\.ht {
        deny all;
    }
}
