from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from pitchcopytrade.db.models.accounts import AuthorProfile, User
from pitchcopytrade.db.models.audit import AuditEvent
from pitchcopytrade.db.models.catalog import Instrument, LeadSource, Strategy
from pitchcopytrade.db.models.catalog import SubscriptionProduct
from pitchcopytrade.db.models.commerce import LegalDocument, Payment, PromoCode, Subscription
from pitchcopytrade.db.models.content import Recommendation
from pitchcopytrade.db.models.enums import RecommendationStatus


class AuthorRepository(Protocol):
    async def count_author_strategies(self, author_id: str) -> int: ...

    async def count_author_recommendations(
        self,
        author_id: str,
        *,
        statuses: Sequence[RecommendationStatus] | None = None,
    ) -> int: ...

    async def list_author_strategies(self, author_id: str) -> list[Strategy]: ...

    async def list_active_instruments(self) -> list[Instrument]: ...

    async def list_author_recommendations(self, author_id: str) -> list[Recommendation]: ...

    async def get_author_recommendation(self, author_id: str, recommendation_id: str) -> Recommendation | None: ...

    async def get_author_by_user_id(self, user_id: str) -> AuthorProfile | None: ...

    def add(self, entity: object) -> None: ...

    async def delete(self, entity: object) -> None: ...

    async def flush(self) -> None: ...

    async def commit(self) -> None: ...

    async def refresh(self, entity: object) -> None: ...


class AccessRepository(Protocol):
    async def user_has_active_access(self, user_id: str) -> bool: ...

    async def list_user_visible_recommendations(
        self,
        *,
        user_id: str,
        limit: int = 20,
    ) -> list[Recommendation]: ...

    async def get_user_visible_recommendation(
        self,
        *,
        user_id: str,
        recommendation_id: str,
    ) -> Recommendation | None: ...

    async def get_user_by_telegram_id(self, telegram_user_id: int) -> User | None: ...

    async def commit(self) -> None: ...

    async def list_user_reminder_events(self, *, user_id: str, limit: int = 20) -> list[AuditEvent]: ...

    async def get_notification_preferences(self, *, user_id: str) -> dict[str, bool]: ...

    async def save_notification_preferences(self, *, user_id: str, preferences: dict[str, bool]) -> dict[str, bool]: ...


class PublicRepository(Protocol):
    async def list_public_strategies(self) -> list[Strategy]: ...

    async def get_public_strategy_by_slug(self, slug: str) -> Strategy | None: ...

    async def get_public_product(self, product_id: str) -> SubscriptionProduct | None: ...

    async def get_public_product_by_slug(self, slug: str) -> SubscriptionProduct | None: ...

    async def list_active_checkout_documents(self) -> list[LegalDocument]: ...

    async def find_active_promo_by_code(self, code: str) -> PromoCode | None: ...

    async def get_lead_source_by_name(self, name: str) -> LeadSource | None: ...

    async def find_user_by_email(self, email: str) -> User | None: ...

    async def get_user_by_telegram_id(self, telegram_user_id: int) -> User | None: ...

    async def get_user_payment(self, *, telegram_user_id: int, payment_id: str) -> Payment | None: ...

    async def get_user_subscription(self, *, telegram_user_id: int, subscription_id: str) -> Subscription | None: ...

    def add(self, entity: object) -> None: ...

    async def commit(self) -> None: ...

    async def refresh(self, entity: object) -> None: ...


class AuthRepository(Protocol):
    async def get_user_by_identity(self, identity: str) -> User | None: ...

    async def get_user_by_id(self, user_id: str) -> User | None: ...
